site_name: Pyvista Gallery
theme: material    # This theme is mandatory for now, see below

plugins:
  - gallery:
      examples_dirs: docs/examples          # path to your example scripts
      gallery_dirs: docs/generated/gallery  # where to save generated gallery
      conf_script: docs/gallery_conf.py

  - search  # make sure the search plugin is still enabled

nav:
  - Home: index.md
  - Gallery: generated/gallery/index.md